{{- if .Values.secret.create }}
{{- $adminToken := required "secret.jupyterhubAdminToken is required when secret.create=true" .Values.secret.jupyterhubAdminToken }}
{{- $hostKey := required "secret.sshHostKey is required when secret.create=true" .Values.secret.sshHostKey }}
{{- if eq .Values.jupyterhub.adminTokenSecret.name .Values.ssh.hostKeySecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ssh.hostKeySecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "containerssh-jhub.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.jupyterhub.adminTokenSecret.key }}: {{ $adminToken | quote }}
  {{ .Values.ssh.hostKeySecret.key }}: |-
{{ $hostKey | indent 4 }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jupyterhub.adminTokenSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "containerssh-jhub.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.jupyterhub.adminTokenSecret.key }}: {{ $adminToken | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ssh.hostKeySecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "containerssh-jhub.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.ssh.hostKeySecret.key }}: |-
{{ $hostKey | indent 4 }}
{{- end }}
{{- end }}
